# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := CommandLineShell
ARDUINO_LIBS := AceCommon AceRoutine
include ../../../UnixHostDuino/UnixHostDuino.mk
