# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloCoroutineWithProfiler
ARDUINO_LIBS := AceCommon AceRoutine
include ../../../EpoxyDuino/EpoxyDuino.mk
