pipeline {
    agent { label 'master' }
    environment {
        AUNITER_ARDUINO_BINARY = '/var/lib/jenkins/arduino-1.8.5/arduino'
    }
    stages {
        stage('Setup') {
            steps {
                dir('AUniter') {
                    git url: 'https://github.com/bxparks/AUniter',
                        branch: 'develop'
                }
                dir('libraries/AUnit') {
                    git url: 'https://github.com/bxparks/AUnit',
                        branch: 'develop'
                }
            }
        }
        stage('Verify Examples') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceRoutine/tests/auniter.conf \
                    --boards nano \
                    libraries/AceRoutine/examples/*"
            }
        }
        stage('Verify Tests') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceRoutine/tests/auniter.conf \
                    --boards nano \
                    --verify \
                    libraries/AceRoutine/tests/*Test"
            }
        }
        stage('Test') {
            steps {
                sh "AUniter/auniter.sh --test \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceRoutine/tests/auniter.conf \
                    --boards nano:/dev/ttyUSB0 \
                    libraries/AceRoutine/tests/*Test"
            }
        }
    }
}
