# See https://github.com/bxparks/UnixHostDuino for documentation
# about using UnixHostDuino to compile and run AUnit tests natively on Linux or
# MacOS.

APP_NAME := AceRoutineTest
ARDUINO_LIBS := AUnit AceRoutine
include ../../../UnixHostDuino/UnixHostDuino.mk
