# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Udiv1000
ARDUINO_LIBS := AceRoutine
include ../../../UnixHostDuino/UnixHostDuino.mk
