# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ChannelTest
ARDUINO_LIBS := AUnit AceRoutine
include ../../../EpoxyDuino/EpoxyDuino.mk
