# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := SoundManager
ARDUINO_LIBS := AceRoutine AceCommon
EXTRA_CXXFLAGS := -g
include ../../../EpoxyDuino/EpoxyDuino.mk
